### ISSUE TITLE
Would this work with Sonic Pi?

### ISSUE THREAD

**Issue by cormullion** [fundamental/OSC.jl#13]
Hi! Do you think this package would work well with [Sonic Pi](https://sonic-pi.net) for live coding? I've seen some Python interfacing, and they use Ruby in the Sonic Pi IDE, so I was wondering whether it would be worth trying to get Julia to work as a coding tool that interacts with Sonic Pi.

**Comment by fundamental** [comment]
It should work well enough in terms of sending messages to sonic pi, but beyond that I cannot say.

**Comment by cormullion** [comment]
Thanks. I'll give it a go, although I'll have to learn about sockets first, I think... 😄

**Comment by cormullion** [comment]
I managed to get it working.

```julia
using OpenSoundControl, Sockets

"""
In Sonic Pi, start listening to OSC:

live_loop :foo do
  use_osc_logging true
  use_real_time
  s = sync "/osc*/s"
  begin
    eval s[0]
  rescue
  end
end

"""

const SONICPI = ip"127.0.0.1"

const SOCKET = UDPSocket()

function live_loop(name::Symbol, body)
    loopname = string(":", name)
    message("live_loop $(loopname) do
        $(body)
    end")
end

function live_loop(name::String, body)
    loopname = string(":", Symbol(name))
    message("live_loop $(loopname) do
        $(body)
    end")
end

live_loop(:l1, "
    use_bpm 60
    sample :loop_amen, amp: 0.4
    sample :bd_haus, amp: 0.9
    sleep 1.78
    ")
```
