### ISSUE TITLE
Zero-based indexing

### ISSUE THREAD

**Issue by ssfrr** [fundamental/OSC.jl#3]
Accessing the fields of an `OscMsg` is currently using zero-based indexing, which isn't consistent with other Julia code. I know that the one-based versus zero-based indexing is something of a matter of taste, but it seems like it would be easier for users of your library if they(we) didn't have to remember that this library indexes differently than the rest of the Julia code we use.

Would you consider a PR to remove the offset code and switch to 1-based indexing?

Thanks.

**Comment by fundamental** [comment]
Certainly.

The zero based indexing is just a quirk resulting from porting it from C that I must have overlooked.
