### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by nico202** [fundamental/OSC.jl#7]
Hi, I just fixed the code to make it compatible with julia 0.5 and then realized it was already fixed but not tagged, so I was on an older version.
Could you please tag it like 0.0.2 to make it available to julia Pkg.update()? Thanks, Nicolò

**Comment by fundamental** [comment]
The package has been tagged and the update to METADATA is pending at https://github.com/JuliaLang/METADATA.jl/pull/9877

**Comment by fundamental** [comment]
v0.1.0 is now in METADATA
